spring.application.name=inventory

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory-db
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000